### ISSUE TITLE
inst_rom missing

### ISSUE THREAD

**Issue by chaujohnthan** [Pipepw/MIPS_CPU#1]

**Comment by Pipepw** [comment]
what do you mean, missing the inst_rom.data?

**Comment by chaujohnthan** [comment]
initial $readmemh("E:/Virtual Machines/VMsharefile/inst_rom.data",inst_mem);

**Comment by Pipepw** [comment]
the content of the inst_rom is machine language. it's need you to write it. you can compile MIPS assembly language as machine language
